title: Blog - Tormenta Ascension
email: cunhakaua2@gmail.com
description: >-
  Blog oficial de notícias, eventos e atualizações de Tormenta Ascension.
baseurl: "/tormenta-ascension-blog"
url: "https://Kaua-da-Cunha-Rodrigues.github.io"

theme: minima
plugins:
  - jekyll-feed
